### PR TITLE
Update addons.md

### PR DESCRIPTION
**Pull request by NotLewUwU**
Just added my addon

### CODE REVIEW

**Comment by andrei1058** [comment]
there are conflicts

**Comment by JT122406** [comment]
@NotLewUwU Does this and #54 need to be open or can this be closed and added to that?

**Comment by OPADILOP** [comment]
@NotLewUwU The bossbar plugin is already added to the wiki. You might close this pull request as soon as possible.

**Review by OPADILOP — COMMENTED** [review]
No need already added to the wiki.

**Pull request closed without merging**
